env = Environment()
env.Replace(CXXFLAGS=['-O3','-Wall','-ansi','-pedantic', '-std=c++11'],
            LIBS=['pthread'])
env.SharedLibrary('salpa', ['LocalFit.cpp'])
env.Program('salpa', ['LocalFit.cpp', 'posthoctasked.cpp'])
env.Program('salpa-altthread', ['LocalFit.cpp', 'posthocthreaded.cpp'])
env.Program('salpa-nothread', ['LocalFit.cpp', 'posthocsalpa.cpp'])
#env.Program('tqtest', ['TQTest.cpp'])