on:
  push:
    tags:
      - "v*"
      
name: Upload wheel linux


permissions:
  contents: write
  id-token: write


jobs:
  build:
    name: Build wheel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Install requirements for building binary
        run: .github/get-build-requirements-linux
      - name: Build wheel
        working-directory: ./python
        run: python -m build
      - name: Upload wheel
        uses: softprops/action-gh-release@v2
        with:
          files: build/salpa*whl
          token: ${{github.TOKEN}}
          